<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();
        \App\Models\Product\Product::factory(30000)->create();
        // $now = Carbon::now();

        // $countries = array(
        //     array('code' => 'AF', 'name' => "Afghanistan", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'AL', 'name' => "Albania", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'DZ', 'name' => "Algeria", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'AS', 'name' => "American Samoa", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'AD', 'name' => "Andorra", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'AO', 'name' => "Angola", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'AI', 'name' => "Anguilla", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'AQ', 'name' => "Antarctica", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'AG', 'name' => "Antigua And Barbuda", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'AR', 'name' => "Argentina", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'AM', 'name' => "Armenia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'AW', 'name' => "Aruba", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'AU', 'name' => "Australia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'AT', 'name' => "Austria", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'AZ', 'name' => "Azerbaijan", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'BS', 'name' => "Bahamas The", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'BH', 'name' => "Bahrain", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'BD', 'name' => "Bangladesh", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'BB', 'name' => "Barbados", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'BY', 'name' => "Belarus", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'BE', 'name' => "Belgium", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'BZ', 'name' => "Belize", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'BJ', 'name' => "Benin", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'BM', 'name' => "Bermuda", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'BT', 'name' => "Bhutan", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'BO', 'name' => "Bolivia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'BA', 'name' => "Bosnia and Herzegovina", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'BW', 'name' => "Botswana", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'BV', 'name' => "Bouvet Island", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'BR', 'name' => "Brazil", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'IO', 'name' => "British Indian Ocean Territory", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'BN', 'name' => "Brunei", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'BG', 'name' => "Bulgaria", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'BF', 'name' => "Burkina Faso", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'BI', 'name' => "Burundi", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'KH', 'name' => "Cambodia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'CM', 'name' => "Cameroon", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'CA', 'name' => "Canada", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'CV', 'name' => "Cape Verde", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'KY', 'name' => "Cayman Islands", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'CF', 'name' => "Central African Republic", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'TD', 'name' => "Chad", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'CL', 'name' => "Chile", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'CN', 'name' => "China", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'CX', 'name' => "Christmas Island", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'CC', 'name' => "Cocos (Keeling) Islands", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'CO', 'name' => "Colombia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'KM', 'name' => "Comoros", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'CG', 'name' => "Congo", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'CD', 'name' => "Congo The Democratic Republic Of The", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'CK', 'name' => "Cook Islands", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'CR', 'name' => "Costa Rica", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'CI', 'name' => "Cote D Ivoire (Ivory Coast)", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'HR', 'name' => "Croatia (Hrvatska)", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'CU', 'name' => "Cuba", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'CY', 'name' => "Cyprus", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'CZ', 'name' => "Czech Republic", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'DK', 'name' => "Denmark", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'DJ', 'name' => "Djibouti", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'DM', 'name' => "Dominica", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'DO', 'name' => "Dominican Republic", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'TP', 'name' => "East Timor", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'EC', 'name' => "Ecuador", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'EG', 'name' => "Egypt", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'SV', 'name' => "El Salvador", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'GQ', 'name' => "Equatorial Guinea", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'ER', 'name' => "Eritrea", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'EE', 'name' => "Estonia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'ET', 'name' => "Ethiopia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'XA', 'name' => "External Territories of Australia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'FK', 'name' => "Falkland Islands", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'FO', 'name' => "Faroe Islands", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'FJ', 'name' => "Fiji Islands", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'FI', 'name' => "Finland", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'FR', 'name' => "France", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'GF', 'name' => "French Guiana", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'PF', 'name' => "French Polynesia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'TF', 'name' => "French Southern Territories", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'GA', 'name' => "Gabon", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'GM', 'name' => "Gambia The", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'GE', 'name' => "Georgia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'DE', 'name' => "Germany", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'GH', 'name' => "Ghana", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'GI', 'name' => "Gibraltar", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'GR', 'name' => "Greece", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'GL', 'name' => "Greenland", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'GD', 'name' => "Grenada", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'GP', 'name' => "Guadeloupe", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'GU', 'name' => "Guam", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'GT', 'name' => "Guatemala", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'XU', 'name' => "Guernsey and Alderney", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'GN', 'name' => "Guinea", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'GW', 'name' => "Guinea-Bissau", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'GY', 'name' => "Guyana", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'HT', 'name' => "Haiti", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'HM', 'name' => "Heard and McDonald Islands", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'HN', 'name' => "Honduras", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'HK', 'name' => "Hong Kong S.A.R.", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'HU', 'name' => "Hungary", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'IS', 'name' => "Iceland", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'IN', 'name' => "India", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'ID', 'name' => "Indonesia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'IR', 'name' => "Iran", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'IQ', 'name' => "Iraq", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'IE', 'name' => "Ireland", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'IL', 'name' => "Israel", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'IT', 'name' => "Italy", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'JM', 'name' => "Jamaica", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'JP', 'name' => "Japan", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'XJ', 'name' => "Jersey", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'JO', 'name' => "Jordan", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'KZ', 'name' => "Kazakhstan", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'KE', 'name' => "Kenya", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'KI', 'name' => "Kiribati", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'KP', 'name' => "Korea North", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'KR', 'name' => "Korea South", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'KW', 'name' => "Kuwait", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'KG', 'name' => "Kyrgyzstan", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'LA', 'name' => "Laos", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'LV', 'name' => "Latvia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'LB', 'name' => "Lebanon", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'LS', 'name' => "Lesotho", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'LR', 'name' => "Liberia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'LY', 'name' => "Libya", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'LI', 'name' => "Liechtenstein", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'LT', 'name' => "Lithuania", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'LU', 'name' => "Luxembourg", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'MO', 'name' => "Macau S.A.R.", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'MK', 'name' => "Macedonia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'MG', 'name' => "Madagascar", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'MW', 'name' => "Malawi", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'MY', 'name' => "Malaysia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'MV', 'name' => "Maldives", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'ML', 'name' => "Mali", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'MT', 'name' => "Malta", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'XM', 'name' => "Man (Isle of)", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'MH', 'name' => "Marshall Islands", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'MQ', 'name' => "Martinique", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'MR', 'name' => "Mauritania", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'MU', 'name' => "Mauritius", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'YT', 'name' => "Mayotte", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'MX', 'name' => "Mexico", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'FM', 'name' => "Micronesia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'MD', 'name' => "Moldova", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'MC', 'name' => "Monaco", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'MN', 'name' => "Mongolia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'MS', 'name' => "Montserrat", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'MA', 'name' => "Morocco", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'MZ', 'name' => "Mozambique", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'MM', 'name' => "Myanmar", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'NA', 'name' => "Namibia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'NR', 'name' => "Nauru", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'NP', 'name' => "Nepal", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'AN', 'name' => "Netherlands Antilles", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'NL', 'name' => "Netherlands The", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'NC', 'name' => "New Caledonia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'NZ', 'name' => "New Zealand", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'NI', 'name' => "Nicaragua", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'NE', 'name' => "Niger", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'NG', 'name' => "Nigeria", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'NU', 'name' => "Niue", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'NF', 'name' => "Norfolk Island", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'MP', 'name' => "Northern Mariana Islands", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'NO', 'name' => "Norway", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'OM', 'name' => "Oman", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'PK', 'name' => "Pakistan", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'PW', 'name' => "Palau", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'PS', 'name' => "Palestinian Territory Occupied", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'PA', 'name' => "Panama", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'PG', 'name' => "Papua new Guinea", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'PY', 'name' => "Paraguay", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'PE', 'name' => "Peru", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'PH', 'name' => "Philippines", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'PN', 'name' => "Pitcairn Island", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'PL', 'name' => "Poland", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'PT', 'name' => "Portugal", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'PR', 'name' => "Puerto Rico", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'QA', 'name' => "Qatar", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'RE', 'name' => "Reunion", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'RO', 'name' => "Romania", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'RU', 'name' => "Russia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'RW', 'name' => "Rwanda", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'SH', 'name' => "Saint Helena", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'KN', 'name' => "Saint Kitts And Nevis", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'LC', 'name' => "Saint Lucia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'PM', 'name' => "Saint Pierre and Miquelon", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'VC', 'name' => "Saint Vincent And The Grenadines", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'WS', 'name' => "Samoa", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'SM', 'name' => "San Marino", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'ST', 'name' => "Sao Tome and Principe", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'SA', 'name' => "Saudi Arabia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'SN', 'name' => "Senegal", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'RS', 'name' => "Serbia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'SC', 'name' => "Seychelles", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'SL', 'name' => "Sierra Leone", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'SG', 'name' => "Singapore", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'SK', 'name' => "Slovakia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'SI', 'name' => "Slovenia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'XG', 'name' => "Smaller Territories of the UK", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'SB', 'name' => "Solomon Islands", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'SO', 'name' => "Somalia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'ZA', 'name' => "South Africa", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'GS', 'name' => "South Georgia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'SS', 'name' => "South Sudan", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'ES', 'name' => "Spain", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'LK', 'name' => "Sri Lanka", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'SD', 'name' => "Sudan", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'SR', 'name' => "Suriname", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'SJ', 'name' => "Svalbard And Jan Mayen Islands", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'SZ', 'name' => "Swaziland", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'SE', 'name' => "Sweden", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'CH', 'name' => "Switzerland", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'SY', 'name' => "Syria", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'TW', 'name' => "Taiwan", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'TJ', 'name' => "Tajikistan", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'TZ', 'name' => "Tanzania", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'TH', 'name' => "Thailand", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'TG', 'name' => "Togo", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'TK', 'name' => "Tokelau", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'TO', 'name' => "Tonga", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'TT', 'name' => "Trinidad And Tobago", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'TN', 'name' => "Tunisia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'TR', 'name' => "Turkey", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'TM', 'name' => "Turkmenistan", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'TC', 'name' => "Turks And Caicos Islands", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'TV', 'name' => "Tuvalu", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'UG', 'name' => "Uganda", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'UA', 'name' => "Ukraine", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'AE', 'name' => "United Arab Emirates", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'GB', 'name' => "United Kingdom", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'US', 'name' => "United States", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'UM', 'name' => "United States Minor Outlying Islands", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'UY', 'name' => "Uruguay", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'UZ', 'name' => "Uzbekistan", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'VU', 'name' => "Vanuatu", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'VA', 'name' => "Vatican City State (Holy See)", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'VE', 'name' => "Venezuela", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'VN', 'name' => "Vietnam", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'VG', 'name' => "Virgin Islands (British)", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'VI', 'name' => "Virgin Islands (US)", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'WF', 'name' => "Wallis And Futuna Islands", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'EH', 'name' => "Western Sahara", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'YE', 'name' => "Yemen", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'YU', 'name' => "Yugoslavia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'ZM', 'name' => "Zambia", 'created_at' => $now, 'updated_at' => $now),
        //     array('code' => 'ZW', 'name' => "Zimbabwe", 'created_at' => $now, 'updated_at' => $now),
        // );

        // DB::table('countries')->insert($countries);
    }
}
